# Generated by Django 4.0.3 on 2022-04-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_food_size_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('F S', 'F S')], max_length=50, null=True),
        ),
    ]
