# Generated by Django 3.2.3 on 2022-05-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_groceries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodType',
            new_name='FoodMenu',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='type',
            new_name='food_menu',
        ),
        migrations.RenameField(
            model_name='foodmenu',
            old_name='type',
            new_name='name',
        ),
    ]
