# Generated by Django 3.2.3 on 2022-05-11 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20220511_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='resturant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_menu', to='services.resturant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='food_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='services.foodmenu'),
        ),
    ]
