# Generated by Django 3.2.3 on 2022-05-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20220511_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='image',
            field=models.ImageField(default=1, upload_to='menu/'),
            preserve_default=False,
        ),
    ]
