# Generated by Django 4.0.3 on 2022-05-12 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_category'),
        ('services', '0010_foodmenu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='groceries',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groceries', to='configuration.category'),
        ),
        migrations.AddField(
            model_name='resturant',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='groceries',
            name='grocery_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groceries', to='services.groceryshop'),
            preserve_default=False,
        ),
    ]
