# Generated by Django 4.0.3 on 2022-05-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_groceryshop_groceries_category_resturant_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryshop',
            name='image',
            field=models.ImageField(default=1, upload_to='GroceryShops/'),
            preserve_default=False,
        ),
    ]
